/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.assignment.Deeprooted;

import java.util.List;

import com.assignment.Deeprooted.dto.DSMatch;
import com.assignment.Deeprooted.entities.DemandOrder;
import com.assignment.Deeprooted.entities.SupplyOrder;
import com.assignment.Deeprooted.exceptions.NoFileFoundException;
import com.assignment.Deeprooted.services.FileReaderService;
import com.assignment.Deeprooted.services.GenerateOutputServiceImpl;
import com.assignment.Deeprooted.services.IGenerateOutputService;

public class App {
   public static void main(String[] args) {
        try {
            if (args.length != 1) {
              throw new NoFileFoundException("Couldnot find the input file, please provide the input file");
            }
            String filePath = args[0];
            // parse the input file from path provided
            FileReaderService fileReaderService = new FileReaderService(filePath);

            //fetching data from file service
            List<SupplyOrder> supplyOrders=fileReaderService.getSupplyOrders();
            List<DemandOrder> demandOrders=fileReaderService.getDemandOrders();

            //providing the extracted data to service layer
            IGenerateOutputService generateOutputService=new GenerateOutputServiceImpl(supplyOrders, demandOrders);
            //Generated Demand Supply Maches
            List<DSMatch> matches=generateOutputService.getDemandSupplyMatch();
                    
            matches.forEach(System.out::println);
    
          } catch (Exception e) {
            System.out.println(e.getMessage());
          }
        }
}
    



